CODE SEGMENT
ASSUME CS:CODE
ORG 1000H
START:
MOV DX,0FF2BH
MOV AL,82H
OUT DX,AL

LOOP1:MOV DX,0FF29H
IN AL,DX
TEST AL,01H
JNZ LOOP1  ;按下按键跳转 
TEST AL,02H  ;zhenghzuan
JNZ OUTPUT1
TEST AL,04H
JNZ OUTPUT2
JMP LOOP1

OUTPUT1:MOV DX,0FF28H
      MOV AL,03H
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,06H
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,0CH
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,09H
      OUT DX,AL
      CALL DELAY
      JMP LOOP1

OUTPUT2:MOV DX,0FF28H
      MOV AL,09H
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,0CH
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,06H
      OUT DX,AL
      CALL DELAY
      MOV DX,0FF28H
      MOV AL,03H
      OUT DX,AL
      CALL DELAY
      JMP LOOP1

DELAY PROC
      PUSH BX
      PUSH CX
      MOV BL,2
NEXT:MOV CX,416
W10MS:LOOP W10MS
      DEC BL
      JNE NEXT 
      POP CX    
      POP BX
      RET
DELAY ENDP

CODE ENDS 
END START